stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  before_script:
    - cp ${ENV} .env
    - cp ${TEST_ENV} .test.env
    - df -h
    - du -sh /var/lib/docker || true
    - docker system df
    - docker system prune -a -f --volumes
    - rm -rf /var/lib/docker/tmp/*
    - rm -rf /cache/*
    - rm -rf /builds/*
  script:
    - docker build --rm -t booking-api-image .

deploy-job:
  stage: deploy
  script:
    - docker compose -f docker-compose-ci.yml up -d 
