services:
  booking_back_service:
    container_name: 'booking_back'
    build:
      context: .
    # ports:
    #   - "8345:8000"
    networks:
      - myNetwork

  booking_celery_worker_service:
    container_name: 'booking_celery_worker'
    build:
      context: .
    networks:
      - myNetwork
    env_file:
      - .env
    command: "celery --app=app.tasks.celery_app:celery_instance worker -l INFO"

networks:
  myNetwork:
    external: true