services:
  booking_back_service:
    container_name: 'booking_back'
    image: booking-api-image:latest
    networks:
      - myNetwork

  booking_celery_worker_service:
    container_name: 'booking_celery_worker'
    image: booking-api-image:latest
    networks:
      - myNetwork
    command: "celery --app=app.tasks.celery_app:celery_instance worker -l INFO"

networks:
  myNetwork:
    external: true